// Exportaciones de todas las entidades
export { Actividad } from './actividad.entity';
export { Anotacion } from './anotacion.entity';
export { Asistencia } from './asistencia.entity';
export { Aula } from './aula.entity';
export { Cronograma } from './cronograma.entity';
export { Curso } from './curso.entity';
export { Estudiante } from './estudiante.entity';
export { Evaluacion } from './evaluacion.entity';
export { Grado } from './grado.entity';
export { Informe } from './informe.entity';
export { Matricula } from './matricula.entity';
export { Notas } from './notas.entity';
export { Padre } from './padre.entity';
export { Pago } from './pago.entity';
export { Rol } from './rol.entity';
export { TipoAnotacion } from './tipo-anotacion.entity';
export { Trabajador } from './trabajador.entity';
export { Usuario } from './usuario.entity';