export { Roles as Role } from './roles.entity';
export { Trabajador as Person } from './trabajador.entity';
export { Usuario as User } from './usuario.entity';
export { Grado as Grade } from './grado.entity';
export { Subject } from './subject.entity';
export { Estudiante } from './estudiante.entity';
export { PadresEstudiantes } from './padre_Estudiante.entity';
export { Matricula } from './matricula.entity';
export { Aula } from './aula.entity';
export { Curso } from './curso.entity';
export { Asistencia } from './asistencia.entity';
export { Evaluacion } from './evaluaciones.entity';
export { Informe } from './informe.entity';
export { Notas } from './notas.entity';
export { Actividades } from './actividades.entity';
export { Cronograma } from './cronograma.entity';
